### ISSUE TITLE
 java.lang.IndexOutOfBoundsException: Invalid item position -2(-2). Item count:20

### ISSUE THREAD

**Issue by shunyxu** [leochuan/ViewPagerLayoutManager#10]
快速滑动必现这个闪退 
java.lang.IndexOutOfBoundsException: Invalid item position -2(-2). Item count:20
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5466)
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                                  at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                                  at rouchuan.customlayoutmanager.ViewPagerLayoutManager.layoutItems(ViewPagerLayoutManager.java:299)
                                                                                  at rouchuan.customlayoutmanager.ViewPagerLayoutManager.scrollHorizontallyBy(ViewPagerLayoutManager.java:262)
                                                                                  at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4722)
                                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:898)
                                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:700)
                                                                                  at android.view.Choreographer.doFrame(Choreographer.java:632)
                                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:884)
                                                                                  at android.os.Handler.handleCallback(Handler.java:815)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                  at android.os.Looper.loop(Looper.java:238)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6016)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:937)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:798)

**Comment by leochuan** [comment]
@shunyxu 好了 拉下新的代码 应该没问题了
