### ISSUE TITLE
Items Cannot be Navigated via Pointer

### ISSUE THREAD

**Issue by djnotes** [leochuan/ViewPagerLayoutManager#26]
In devices like Android TV and Android set-top boxes, there is often a remote-controller pointer that is used to navigate activities and lists. In a model I am using (MXQ-4K), the items of list created using ViewPagerLayoutManager cannot be selected or navigated. Other items like buttons and floating action buttons are selectable. Is there a method available in the library to support such navigation?

You can check out the app in action here: 
https://youtu.be/glppT8PTmYE

**Comment by leochuan** [comment]
@jasonMisaq No available method for supporting navigation now. After google, it said that I need to rewrite the `onFocusSearchFailed` method. I will support that in next release.

**Comment by jasonMisaq** [comment]
Is there no way to make the RecyclerView receive such events without rewriting your code? I need this feature very badly. It struck me to use simple RecyclerView instead of ViewPagerLayoutManager, but it does not support infinite scroll.

**Comment by leochuan** [comment]
I am working with it recently, Basically I’ve rewrote all the methods it needs and it works fine except infinite scroll is enabled..Maybe it still needs couple days for me to solve this problem

**Comment by leochuan** [comment]
@jasonMisaq I think it's done. try version `2.0.6`

fix by ac76e71b671d5b55d6ab2e25badb65b66d8411c2

**Comment by jasonMisaq** [comment]
Thanks. Why did you remove CenterScrollListener?

**Comment by jasonMisaq** [comment]
When I select an item with keyboard, I get ArithmeticException:   
```
 FATAL EXCEPTION: main
                                                                    Process: com.zood.mediaplayer, PID: 8753
                                                                    java.lang.ArithmeticException: divide by zero
                                                                        at com.leochuan.ViewPagerLayoutManager.getCurrentPosition(ViewPagerLayoutManager.java:746)
                                                                        at com.leochuan.ViewPagerLayoutManager.onAddFocusables(ViewPagerLayoutManager.java:403)
                                                                        at android.support.v7.widget.RecyclerView.addFocusables(RecyclerView.java:2581)
                                                                        at android.view.ViewGroup.addFocusables(ViewGroup.java:1221)
                                                                        at android.view.ViewGroup.addFocusables(ViewGroup.java:1221)
                                                                        at android.view.ViewGroup.addFocusables(ViewGroup.java:1221)
                                                                        at android.view.ViewGroup.addFocusables(ViewGroup.java:1221)
                                                                        at android.view.ViewGroup.addFocusables(ViewGroup.java:1221)
                                                                        at android.view.ViewGroup.addFocusables(ViewGroup.java:1221)
                                                                        at android.view.View.addFocusables(View.java:10465)
                                                                        at android.view.FocusFinder.findNextFocus(FocusFinder.java:108)
                                                                        at android.view.FocusFinder.findNextFocus(FocusFinder.java:80)
                                                                        at android.view.ViewRootImpl.focusSearch(ViewRootImpl.java:6186)
                                                                        at android.view.ViewRootImpl.leaveTouchMode(ViewRootImpl.java:4088)
                                                                        at android.view.ViewRootImpl.ensureTouchModeLocally(ViewRootImpl.java:4021)
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1710)
                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
                                                                        at android.view.Choreographer.doFrame(Choreographer.java:658)
                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
                                                                        at android.os.Handler.handleCallback(Handler.java:789)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                        at android.os.Looper.loop(Looper.java:164)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by leochuan** [comment]
`CenterScrollListener` was replaced by `CenterSnapHelper` It's more smooth, you could use it like `new CenterScrollListener().attachToRecyclerView(recyclerView)`

You should handle the effect of focused view on your own, like write a `selector` and determine the color of all the state.

About the crash..Did you layout all the item in the same place? cause when the `interval` is zero, `VPLM` will totally overlap all the items and it's meaningless

**Comment by leochuan** [comment]
Try `2.0.7`.. I fixed the crash.
