### ISSUE TITLE
Exception when  try remove first item

### ISSUE THREAD

**Issue by landarskiy** [leochuan/ViewPagerLayoutManager#54]
After remove first element and call notifyItemRangeRemoved(0,1) in adapter I have got a exception
```
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 0(offset:-1).state:5 android.support.v7.widget.RecyclerView{bcf2aea VFED..... ......I. 0,360-1080,1474 #7f090167 app:id/recyclerView}
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5817)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at com.leochuan.ViewPagerLayoutManager.onLayoutChildren(ViewPagerLayoutManager.java:379)
```

**Comment by leochuan** [comment]
Thx, I think it has been fixed now, try 2.0.17.

**Comment by leveychen** [comment]
改了这个之后，在只有两张图片的时候刷新 adapter 有小概率出现闪屏，图片无限闪动。还原之前版本的代码就不会有这个问题

**Comment by leochuan** [comment]
@leveychen `notifyDataSetChange`  还是 `notifyItemChanged` `notifyItemRangeChanged` 这些？

**Comment by leveychen** [comment]
@leochuan 
notifyDataSetChanged
场景是这样的，网络获取图片，然后 
adapter.setDatas()
adapter.notifyDataSetChanged()
在只有两张图片set进去的情况下，有一定概率出现图片闪动
